### PR TITLE
Make Auto Factory work with bazel 0.16.0

### PR DESCRIPTION
**Pull request by jianglai**
Bazel 0.16.0 uses Java 9 to compile and as a result the `javax.annotation.Generated` class is no longer provided by the default module. Add an explicit dependency on it for `@com_google_auto_factory` target work again.

I tested by building a [dummy example](https://github.com/jianglai/auto_factory_example) with closure rules 0.8.0 which failed:

```
ERROR: /usr/local/google/home/jianglai/auto_factory_example/BUILD:1:1: Building libauto_factory_example.jar (1 source file) and runn
ing annotation processors (AutoFactoryProcessor) failed (Exit 1)                       
error: Failed to process @AutoFactory annotations:
  java.lang.NoClassDefFoundError: javax/annotation/Generated                                                                
        at com.google.auto.factory.processor.FactoryWriter.writeFactory(FactoryWriter.java:65)                                   
        at com.google.auto.factory.processor.AutoFactoryProcessor.doProcess(AutoFactoryProcessor.java:162)
        at com.google.auto.factory.processor.AutoFactoryProcessor.process(AutoFactoryProcessor.java:87)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.jav
a:884)                                                        
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
        at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:110)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$2.invokeJavac(SimpleJavaLibraryBuilder.java:122)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.j
ava:54)                                                       
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:125)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:133)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
  Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)             
        ... 22 more                                     
Target //:auto_factory_example failed to build  
```

Switching to the locally patched closure rules, the build succeeded.

```
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //:auto_factory_example (23 packages loaded).
INFO: Found 1 target...
Target //:auto_factory_example up-to-date:
  bazel-bin/libauto_factory_example.jar
INFO: Elapsed time: 2.075s, Critical Path: 1.74s
INFO: 5 processes: 4 linux-sandbox, 1 worker.
INFO: Build completed successfully, 7 total actions
```

### CODE REVIEW

**Comment by jianglai** [comment]
PS: I just realized that the source of truth is hosted internally. Please let me know if you prefer me to submit a CL internally instead, @jart.

**Comment by jart** [comment]
@dslomov is leading the project now.

**Comment by jianglai** [comment]
Ping @dslomov.

**Comment by jianglai** [comment]
Merged internally.
